// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXTyRC1AqelkWp00ZojBFKdMVyI2pt0WI',
    appId: '1:402017355970:web:6b49493fecffa941d0d35b',
    messagingSenderId: '402017355970',
    projectId: 'chat-app-15532',
    authDomain: 'chat-app-15532.firebaseapp.com',
    storageBucket: 'chat-app-15532.firebasestorage.app',
    measurementId: 'G-W6HNJ2V1WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcEWOjjR2Zw7mJ1lYldbnk-Q6lTt7NmWs',
    appId: '1:402017355970:android:6401518dbf1c0594d0d35b',
    messagingSenderId: '402017355970',
    projectId: 'chat-app-15532',
    storageBucket: 'chat-app-15532.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8L7VnF4O9C71wVoh-lJEI-D7zRuGZF_A',
    appId: '1:402017355970:ios:cfb747cf54a128c8d0d35b',
    messagingSenderId: '402017355970',
    projectId: 'chat-app-15532',
    storageBucket: 'chat-app-15532.firebasestorage.app',
    iosBundleId: 'com.example.mychatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8L7VnF4O9C71wVoh-lJEI-D7zRuGZF_A',
    appId: '1:402017355970:ios:cfb747cf54a128c8d0d35b',
    messagingSenderId: '402017355970',
    projectId: 'chat-app-15532',
    storageBucket: 'chat-app-15532.firebasestorage.app',
    iosBundleId: 'com.example.mychatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXTyRC1AqelkWp00ZojBFKdMVyI2pt0WI',
    appId: '1:402017355970:web:609e1b526f15b372d0d35b',
    messagingSenderId: '402017355970',
    projectId: 'chat-app-15532',
    authDomain: 'chat-app-15532.firebaseapp.com',
    storageBucket: 'chat-app-15532.firebasestorage.app',
    measurementId: 'G-KR78CZ21C0',
  );
}
